### ISSUE TITLE
Respectful Suggestions to Enhance MEBOCOST

### ISSUE THREAD

**Issue by wu-yc** [zhengrongbin/MEBOCOST#19]
Thank you, Rongbin, for developing and sharing the MEBOCOST tool. This Python-based approach for inferring cell-cell communication mediated by metabolites using single-cell RNA-seq data is an innovative idea. I appreciate you making this tool openly available. The approach makes logical sense and is grounded in molecular biology fundamentals.

I have a couple of suggestions that may help improve the algorithm:

1. Estimating intracellular metabolite levels based on gene expression may have limitations, as metabolites can also be present extracellularly in the stroma and may not spread evenly within cells. Incorporating factors like metabolite diffusion could enhance metabolic signaling predictions.

2. Calculating the product of E[i] and M[i] is clever, but may be prone to distortion from outliers. If a single cell has an extremely high E[i] or M[i] value, it could skew the overall interaction score. Using a statistical approach robust to outliers could help avoid this issue.

Overall, thank you again for creating MEBOCOST and sharing it openly. I appreciate the thought and effort you put into designing this algorithm and implementing it as user-friendly software. It's an impressive contribution that I expect will accelerate research in this emerging area. Great work!

**Comment by zhengrongbin** [comment]
Thanks for your interests, and for your constructive suggestions. Here are my responses:
1. We may mislead you, but I think the metabolite inference based on enzyme gene expression is more likely qualitative existence rather than absolute metabolite levels. Such a qualitative inference does work for communication analysis. You are right, metabolites spread in the microenvironment. The metabolite diffusion should be important, and we ever think about it in the communication modeling. However, I am not sure if there are any data available to tell the metabolite diffusion or stability in the microenvironment. That's the reason that we didn't consider it in the current analysis. Please feel free to remind me if you have any ideas. I appreciate it. 

2. It is interesting to think about the statistical approaches for aggregating values across single cells. I remember we indeed compared different methods and finally decided to take average for expression values across cells in the same cell type, and take products for enzyme and sensor gene expression for sender and receiver cell types. 
 
But, any further conceptual and technical suggestions are absolutely welcome. Please feel free to send me email if you want to discuss more details about your suggestions. I'd love to improve our modeling by incorporating more considerations. Thank you again.
