### ISSUE TITLE
met_ann = None, but used in infflux  and efflux (vignette)

### ISSUE THREAD

**Issue by NeuralBind** [zhengrongbin/MEBOCOST#24]
Hello, 

First thanks for this nice tool!

In the vignettes, both efflux and infflux use in the met_ann which is none in the whole script. How can i access this ?

efflux_mat = pd.merge(efflux_mat, met_ann[['Secondary_HMDB_ID', 'metabolite']]

**Comment by zhengrongbin** [comment]
Hi this should be fixed in the version 1.0.4 at https://github.com/kaifuchenlab/MEBOCOSTPlease try it and let me know if you still have question. Thanks!Best Regards!Rongbin ZhengOn Jun 18, 2024, at 7:53 AM, NeuralBind ***@***.***> wrote:﻿
Hello,
First thanks for this nice tool!
In the vignettes, both efflux and infflux use in the met_ann which is none in the whole script. How can i access this ?
efflux_mat = pd.merge(efflux_mat, met_ann[['Secondary_HMDB_ID', 'metabolite']]

**Comment by NeuralBind** [comment]
oh, just saw there was another repository. Thanks! I will try it out.
