### ISSUE TITLE
Error in infer_pathway

### ISSUE THREAD

**Issue by aboutfanfan** [zhengrongbin/MEBOCOST#27]
Thanks a lot for your package MEBOCOST! However, when I run the module "Inference of pathway to the communications", there are some error(picture is attached) . Could you give me some advice to deal with this problem? 

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

I would also like to ask two small questions:
a. Which reference signal pathway gmt file is used for pathway inference? I did not see this part mentioned in your article.
b. Is it possible to compare the differences in pathways/metabolites/sender ~ receiver under **different conditions**?

Thank you!

<img width="760" alt="image" src="https://github.com/zhengrongbin/MEBOCOST/assets/126056627/3d1dfae3-ebbd-46ee-92b3-b06383eda1fe">

**Comment by zhengrongbin** [comment]
Hi Thanks for your interest in mebocost. The error seems to me due to the numpy version problem. Please check your numpy version, probably you need to downgrade to a lower version. 

answers to your questions:
a. Which reference signal pathway gmt file is used for pathway inference? I did not see this part mentioned in your article.
Anwser: it is KEGG pathways.

b. Is it possible to compare the differences in pathways/metabolites/sender ~ receiver under different conditions?
Anwser: unfortunately, it does not support analyses for different conditions. We are actually developing the pathway analysis module, we will consider to enable it. Thanks for the question.
